# Generated by Django 4.1 on 2022-08-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistDomain',
            fields=[
                ('domain', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WhitelistDomain',
            fields=[
                ('domain', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
